config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :master_report
      get :merge
      post :merge_execute
    end
    collection do
      get :search
    end
  end
  resources :mettings
  resources :reports do
    collection do
      get :master
    end
  end
  root to: "mettings#index"
end

app/models/metting.rb
class Metting < ApplicationRecord
  has_many :metting_users, dependent: :destroy
  has_many :users, through: :metting_users

  has_attached_file :gtm_file

  validates_presence_of :name, :date, :gtm_file
  validates_attachment_content_type :gtm_file, content_type: [
    'application/vnd.ms-excel',
    'application/xls',
    'application/x-ole-storage'
  ]

end

app/controllers/mettings_controller.rb
class MettingsController < ApplicationController
  before_action :set_metting, only: [:show, :edit, :update, :destroy]

  # GET /mettings
  # GET /mettings.json
  def index
    @mettings = Metting.all
  end

  # GET /mettings/1
  # GET /mettings/1.json
  def show
    @users = @metting.users
  end

  # GET /mettings/new
  def new
    @metting = Metting.new
  end

  # GET /mettings/1/edit
  def edit
    redirect_to mettings_url
  end

  # POST /mettings
  # POST /mettings.json
  def create
    import = MettingImport.new(metting_params)
    @metting = import.metting

    respond_to do |format|
      if import.save
        format.html { redirect_to @metting, notice: 'Metting was successfully created.' }
        format.json { render :show, status: :created, location: @metting }
      else
        format.html { render :new }
        format.json { render json: @metting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mettings/1
  # PATCH/PUT /mettings/1.json
  def update
    redirect_to mettings_url
    respond_to do |format|
      if @metting.update(metting_params)
        format.html { redirect_to @metting, notice: 'Metting was successfully updated.' }
        format.json { render :show, status: :ok, location: @metting }
      else
        format.html { render :edit }
        format.json { render json: @metting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mettings/1
  # DELETE /mettings/1.json
  def destroy
    @metting.destroy
    respond_to do |format|
      format.html { redirect_to mettings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metting
      @metting = Metting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metting_params
      if params[:metting].present?
        params.require(:metting).permit(:name, :gtm_file)
      else
        {}
      end
    end
end

app/helpers/mettings_helper.rb
module MettingsHelper

  def zebra_table(i)
    i.even? ? 'table-primary' : 'table-secondary'
  end

  def gtm_time(date, time_zone = nil, format = nil)
    return '' unless date.present?
    time_zone ||= 'Central America'
    format ||= '%a, %b %d %I:%M %p'
    date.in_time_zone(time_zone).strftime(format)
  end

end

app/views/mettings/_form.html.erb
<%= form_with(model: metting, local: true, multipart: true) do |form| %>
  <% if metting.errors.any? %>
    <div class="alert alert-dismissible alert-danger">
      <% metting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group">
      <%= form.file_field :gtm_file, :class => 'form-control-file', 'aria-describedby' => 'fileHelp' %>
      <small id="fileHelp" class="form-text text-muted">Please select xls GTM file.</small>
    </div>
    <p>
      <%= form.submit 'submit', class: 'btn btn-primary' %>
      <%= link_to 'Back', mettings_path, class: 'btn btn-default ', role: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/mettings/edit.html.erb
<h1>Editing Metting</h1>

<%= render 'form', metting: @metting %>

<%= link_to 'Show', @metting %> |
<%= link_to 'Back', mettings_path %>

app/views/mettings/index.html.erb
<%= page_header([{name: :h1, title: 'Mettings', class: 'display-3'}]) %>

<div class="table-responsive">
  <table class="table table-hover responsive">
    <thead>
    </thead>
    <tbody>
    <% if @mettings.any? %>
      <% @mettings.each_with_index do |metting, index| %>
        <tr class=<%= zebra_table(index) %>>
          <td><strong><%= metting.name %></strong> / <%= gtm_time(metting.date) %></td>
          <td><%= link_to 'GTM File', metting.gtm_file.url, target: '_blank' %></td>
          <td>
            <%= link_to 'Attendees', metting %> |
            <%= link_to 'Destroy', metting, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <div class="alert alert-dismissible alert-primary">
        <strong>Oh snap!</strong> No mettings created yet...
      </div>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Metting', new_metting_path, class: 'btn btn-primary ', role: 'button' %>

app/views/mettings/new.html.erb
<%= page_header([{name: :h1, title: 'New Metting', class: 'display-3'}]) %>

<%= render 'form', metting: @metting %>

app/views/mettings/show.html.erb
<% if notice.present? %>
  <div class="alert alert-dismissible alert-success">
    <%= notice %>
  </div>
<% end %>

<%= page_header([{name: :h1, title: @metting.name.titleize, class: 'display-3'}, {name: :h6, title: gtm_time(@metting.date), class: ''}]) %>

<div class="table-responsive">
  <table class="table table-hover responsive">
    <thead>
    </thead>
    <tbody>
    <% if @users.any? %>
      <% @users.each_with_index do |user, index| %>
        <tr class=<%= zebra_table(index) %>>
          <td><%= user.username %></td>
          <td><%= user.fullname %></td>
          <td>
            <%= link_to 'Report', master_report_user_path(id: user, format: 'csv') %> |
            <%= link_to 'Edit', edit_user_path(user) %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <div class="alert alert-dismissible alert-primary">
        <strong>Oh snap!</strong> No users created yet...
      </div>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Back', mettings_path, class: 'btn btn-default ', role: 'button' %>