config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :master_report
      get :merge
      post :merge_execute
    end
    collection do
      get :search
    end
  end
  resources :mettings
  resources :reports do
    collection do
      get :master
    end
  end
  root to: "mettings#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :metting_users, dependent: :destroy
  has_many :mettings, through: :metting_users

  validates_presence_of :username
  validates_uniqueness_of :username

  def self.all_mettings(sql_where, sql_order, *bind_vars)
    sql = "SELECT
        cj_u.username AS username,
        cj_u.fullname AS fullname,
        GROUP_CONCAT(mu.metting_id ORDER BY mu.metting_id) AS mettings_ids,
        COUNT(mu.metting_id) AS metting_count
      FROM
        users AS cj_u
          CROSS JOIN
        mettings AS cj_mt
          LEFT JOIN
        metting_users AS mu ON cj_u.id = mu.user_id AND cj_mt.id = mu.metting_id"
    sql << sql_where
    sql << " GROUP BY username"
    sql << sql_order
    find_by_sql([sql, *bind_vars])
  end

  def merge!(other)
    super(other, attributes: self.attributes.keys, associations: %w[metting_users]) unless self.id == other.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :master_report, :merge, :merge_execute]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to users_url
  end

  # GET /users/new
  def new
    redirect_to users_url
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    redirect_to users_url
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def master_report
    report = Reports::Single.new(params.merge(user_id: @user.id))

    respond_to do |format|
      format.csv { send_data report.to_csv, filename: "#{@user.username.parameterize(separator: "_")}.csv" }
    end
  end

  def merge
  end

  def search
    @user = User.find_by_id(params[:id])
    @users = []
    @users = User.where("username LIKE ? AND id NOT IN(?)", "#{params[:query]}%", @user.id) if params[:query].present?

    respond_to do |format|
      format.js
    end
  end

  def merge_execute
    if params[:user_ids].present? && params[:user_ids].any?
      User.where(id: params[:user_ids]).each do |user|
        @user.merge!(user)
      end
    end

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :fullname, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-dismissible alert-danger">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <div class="form-group">
      <label class="col-form-label" for="inputDefault">Username</label>
      <%= form.text_field :username, class: 'form-control w-25', placeholder: 'Username' %>
      <label class="col-form-label" for="inputDefault">Email username</label>
      <%= form.text_field :email, class: 'form-control w-25', placeholder: 'Email Username' %>
      <label class="col-form-label" for="inputDefault">Fullname</label>
      <%= form.text_field :fullname, class: 'form-control w-25', placeholder: 'Fullname' %>
    </div>
    <p>
      <%= form.submit 'submit', class: 'btn btn-primary' %>
      <%= link_to 'Back', users_path, class: 'btn btn-default ', role: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= page_header([{name: :h1, title: "Editing #{@user.username.titleize}", class: 'display-3'}]) %>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% if notice.present? %>
  <div class="alert alert-dismissible alert-success">
    <%= notice %>.
  </div>
<% end %>

<%= page_header([{name: :h1, title: 'Users', class: 'display-3'}]) %>

<div class="table-responsive">
  <table class="table table-hover responsive">
    <thead>
    </thead>
    <tbody>
    <% if @users.any? %>
      <% @users.each_with_index do |user, index| %>
        <tr class=<%= zebra_table(index) %>>
          <td><%= user.username %></td>
          <td><%= user.fullname %></td>
          <td><%= user.email %></td>
          <td><%= user.recent? ? content_tag(:i, nil, class: 'fas fa-exclamation', 'data-toggle' => :tooltip,
                  'data-placement' => :top, 'title' => '', 'data-original-title' => :Recent) : '' %></td>
          <td>
            <%= link_to 'Report', master_report_user_path(id: user, format: 'csv') %> |
            <%= link_to 'Edit', edit_user_path(user) %> |
            <%= link_to 'Merge', merge_user_path(user) %> |
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <div class="alert alert-dismissible alert-primary">
        <strong>Oh snap!</strong> No users created yet...
      </div>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/merge.html.erb
<%= page_header([{name: :h1, title: "Merging #{@user.username.titleize}", class: 'display-3'}]) %>

<div class="table-responsive">
  <table class="table table-hover responsive">
    <thead>
    </thead>
    <tbody>
        <tr class='table-success'>
          <td class='text-center'><%= @user.username %></td>
          <td class='text-center'><%= @user.fullname %></td>
          <td class='text-center'><%= @user.email %></td>
        </tr>
    </tbody>
  </table>
</div>

<form class="form-inline my-2 my-lg-0" _lpchecked="1">
  <input class="form-control mr-sm-2" type="text" id='query' placeholder="Search by Username">
  <button type="button" class="btn btn-secondary search">Search</button>
</form>

<p>

<div class="table-responsive" id="merge-results">
</div>

<button type="button" class="btn btn-primary merge">Merge!</button>
<%= link_to 'Back', users_path, class: 'btn btn-default', role: 'button' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/search.js.erb
$("#merge-results").html("<%= escape_javascript(render partial: 'users/tables/merge', locals: {user: @user, users: @users }) %>");

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @user.fullname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>