config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :master_report
      get :merge
      post :merge_execute
    end
    collection do
      get :search
    end
  end
  resources :mettings
  resources :reports do
    collection do
      get :master
    end
  end
  root to: "mettings#index"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    redirect_to master_reports_url
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    redirect_to master_reports_url
  end

  # GET /reports/new
  def new
    redirect_to master_reports_url
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
    redirect_to master_reports_url
  end

  # POST /reports
  # POST /reports.json
  def create
    redirect_to master_reports_url
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    redirect_to master_reports_url
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    redirect_to reports_url
    @report.destroy
    respond_to do |format|
      format.html { redirect_to master_reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def master
    @report = Reports::All.new(params)

    respond_to do |format|
      format.csv { send_data @report.to_csv, filename: 'master.csv'}
      format.js
      format.html
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.fetch(:report, {})
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<%= page_header([{name: :h1, title: "Reports", class: 'display-3'}]) %>

<div class="table-responsive">
  <table class="table table-hover responsive">
    <thead>
    </thead>
    <tbody>
        <tr class='table-primary'>
          <td>Master Report</td>
          <td>
            <%= link_to 'View', master_reports_path() %> |
            <%= link_to 'Export',  master_reports_path(format: 'csv') %>
          </td>
        </tr>
    </tbody>
  </table>
</div>

app/views/reports/master.html.erb
<%= page_header([{name: :h1, title: "Master Report", class: 'display-3'}]) %>

<div class="form-group">
  <select id="multiple-mettings" multiple="multiple">
    <% @report.all_mettings.reverse.each_with_index do |metting, index| %>
      <option value="<%= metting.id %>" <%= index.zero? ? "selected='true'" : '' %>><%= "#{metting.name} #{metting.date.strftime('%Y-%m-%d')}" %></option>
    <% end %>
  </select>
</div>

<div class="form-group">
  <select id="single-filter">
    <option value="1">Username ASC</option>
    <option value="2">Username DESC</option>
    <option value="3">Fullname ASC</option>
    <option value="4">Fullname DESC</option>
    <option value="5">Mettings Attended: High to Low</option>
    <option value="6">Mettings Attended: Low to high</option>
  </select>
</div>

<div class="form-group">
  <%= link_to 'Search', "#", id: 'master-search', class: 'btn btn-primary', role: 'button' %>
</div>

<div class="table-responsive" id="master-all">
  <%= render partial: 'reports/tables/master', locals: {report: @report } %>
</div>

<%= link_to 'Export', '#', id: 'master-export', class: 'btn btn-primary', role: 'button' %>
<%= link_to 'Back', reports_path, class: 'btn btn-default', role: 'button' %>

app/views/reports/master.js.erb
$("#master-all").html("<%= escape_javascript(render partial: 'reports/tables/master', locals: {report: @report }) %>");

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>